substitutions:
  _SERVICE_NAME: teanga

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '.']
    dir: 'functions'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching Apple and Google secrets from Secret Manager..."
        gcloud secrets versions access latest --secret="subscriptions_private_key" > functions/SubscriptionsKey.p8
        gcloud secrets versions access latest --secret="google_services" > functions/google_services.json


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '$_SERVICE_NAME',
      '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
      '--platform', 'managed',
      '--region', 'europe-west1',
      '--allow-unauthenticated'
    ]
